### PR TITLE
chore: Work Open PR from workflow

### LINKED ISSUE #86: Open pull request in IntelliJ
**Is your feature request related to a problem? Please describe.**
If using IntelliJ Ultimate (or any IDE that has the github Pull Request support), propose to open the PR in the IDE.

**Describe the solution you'd like**
The plugin already has a right click menu on the PR list, I believe one "just" needs to add an `AnAction` to the action groups of this menu. The action visibility can be check if the Github plugin is enabled (I believe this is bundled by default).

image

**Describe alternatives you've considered**
Go manually to the PR.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/ghactions-manager/issues/86">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/ghactions-manager/issues/86/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by bric3**
Should be able to open a PR in the toolwindow, but ...Github API doesn't return the PR number when it comes from a PR.

`"event": "pull_request"`

Otherwise it should have fixed #86

### CODE REVIEW

**Comment by bric3** [comment]
For reference: https://github.com/orgs/community/discussions/67891

**Comment by cunla** [comment]
hi, thanks for doing this. let me know when I can test it and merge it.

**Comment by bric3** [comment]
At this point I don't know what I can do as the `pull_request` attribute is not filled in the payload returned by github (for runs that were triggered by a `pull_request` event).

**Comment by cunla** [comment]
It is a known issue: https://github.com/orgs/community/discussions/25220

There is a workaround if you are into implementing it:
Get all pull-requests and compare head commit of a PR to the head commit of the workflow run, something like what this code is doing: https://github.com/potiuk/get-workflow-origin/blob/main/src/main.ts

**Pull request closed without merging**
